//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_Category_Event", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaMaD.Model.Category), "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.Event), true)]
[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_Event_Comment", "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaMaD.Model.Event), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.Comment), true)]
[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_UserProfile_Comment", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaMaD.Model.UserProfile), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.Comment), true)]
[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_Event_Recommendation", "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaMaD.Model.Event), "Recommendation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.Recommendation), true)]
[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_UsersGroup_Recommendation", "UsersGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaMaD.Model.UsersGroup), "Recommendation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.Recommendation), true)]
[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_UsersGroup_UserProfile", "UsersGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Es.Udc.DotNet.PracticaMaD.Model.UsersGroup), "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.UserProfile), true)]
[assembly: EdmRelationshipAttribute("PracticaMaDModel", "UserProfile_UserGroups", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.UserProfile), "UsersGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.UsersGroup))]

#endregion

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class PracticaMaDEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto PracticaMaDEntities usando la cadena de conexión encontrada en la sección 'PracticaMaDEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public PracticaMaDEntities() : base("name=PracticaMaDEntities", "PracticaMaDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto PracticaMaDEntities.
        /// </summary>
        public PracticaMaDEntities(string connectionString) : base(connectionString, "PracticaMaDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto PracticaMaDEntities.
        /// </summary>
        public PracticaMaDEntities(EntityConnection connection) : base(connection, "PracticaMaDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Comment> Comments
        {
            get
            {
                if ((_Comments == null))
                {
                    _Comments = base.CreateObjectSet<Comment>("Comments");
                }
                return _Comments;
            }
        }
        private ObjectSet<Comment> _Comments;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Event> Events
        {
            get
            {
                if ((_Events == null))
                {
                    _Events = base.CreateObjectSet<Event>("Events");
                }
                return _Events;
            }
        }
        private ObjectSet<Event> _Events;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Recommendation> Recommendations
        {
            get
            {
                if ((_Recommendations == null))
                {
                    _Recommendations = base.CreateObjectSet<Recommendation>("Recommendations");
                }
                return _Recommendations;
            }
        }
        private ObjectSet<Recommendation> _Recommendations;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UserProfile> UserProfiles
        {
            get
            {
                if ((_UserProfiles == null))
                {
                    _UserProfiles = base.CreateObjectSet<UserProfile>("UserProfiles");
                }
                return _UserProfiles;
            }
        }
        private ObjectSet<UserProfile> _UserProfiles;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UsersGroup> UsersGroups
        {
            get
            {
                if ((_UsersGroups == null))
                {
                    _UsersGroups = base.CreateObjectSet<UsersGroup>("UsersGroups");
                }
                return _UsersGroups;
            }
        }
        private ObjectSet<UsersGroup> _UsersGroups;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Categories. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Comments. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToComments(Comment comment)
        {
            base.AddObject("Comments", comment);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Events. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEvents(Event @event)
        {
            base.AddObject("Events", @event);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Recommendations. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRecommendations(Recommendation recommendation)
        {
            base.AddObject("Recommendations", recommendation);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UserProfiles. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUserProfiles(UserProfile userProfile)
        {
            base.AddObject("UserProfiles", userProfile);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UsersGroups. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsersGroups(UsersGroup usersGroup)
        {
            base.AddObject("UsersGroups", usersGroup);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Category.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        public static Category CreateCategory(global::System.Int32 id, global::System.String name)
        {
            Category category = new Category();
            category.id = id;
            category.name = name;
            return category;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_Category_Event", "Event")]
        public EntityCollection<Event> Events
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Event>("PracticaMaDModel.FK_Category_Event", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Event>("PracticaMaDModel.FK_Category_Event", "Event", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Comment.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="date">Valor inicial de la propiedad date.</param>
        /// <param name="text">Valor inicial de la propiedad text.</param>
        /// <param name="eventId">Valor inicial de la propiedad eventId.</param>
        /// <param name="userProfileId">Valor inicial de la propiedad userProfileId.</param>
        public static Comment CreateComment(global::System.Int32 id, global::System.Byte[] date, global::System.String text, global::System.Int32 eventId, global::System.String userProfileId)
        {
            Comment comment = new Comment();
            comment.id = id;
            comment.date = date;
            comment.text = text;
            comment.eventId = eventId;
            comment.userProfileId = userProfileId;
            return comment;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] date
        {
            get
            {
                return StructuralObject.GetValidValue(_date);
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.Byte[] _date;
        partial void OndateChanging(global::System.Byte[] value);
        partial void OndateChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String text
        {
            get
            {
                return _text;
            }
            set
            {
                OntextChanging(value);
                ReportPropertyChanging("text");
                _text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("text");
                OntextChanged();
            }
        }
        private global::System.String _text;
        partial void OntextChanging(global::System.String value);
        partial void OntextChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 eventId
        {
            get
            {
                return _eventId;
            }
            set
            {
                OneventIdChanging(value);
                ReportPropertyChanging("eventId");
                _eventId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eventId");
                OneventIdChanged();
            }
        }
        private global::System.Int32 _eventId;
        partial void OneventIdChanging(global::System.Int32 value);
        partial void OneventIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userProfileId
        {
            get
            {
                return _userProfileId;
            }
            set
            {
                OnuserProfileIdChanging(value);
                ReportPropertyChanging("userProfileId");
                _userProfileId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userProfileId");
                OnuserProfileIdChanged();
            }
        }
        private global::System.String _userProfileId;
        partial void OnuserProfileIdChanging(global::System.String value);
        partial void OnuserProfileIdChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_Event_Comment", "Event")]
        public Event Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("PracticaMaDModel.FK_Event_Comment", "Event").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("PracticaMaDModel.FK_Event_Comment", "Event").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Event> EventReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("PracticaMaDModel.FK_Event_Comment", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Event>("PracticaMaDModel.FK_Event_Comment", "Event", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UserProfile_Comment", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("PracticaMaDModel.FK_UserProfile_Comment", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("PracticaMaDModel.FK_UserProfile_Comment", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("PracticaMaDModel.FK_UserProfile_Comment", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("PracticaMaDModel.FK_UserProfile_Comment", "UserProfile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Event : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Event.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="date">Valor inicial de la propiedad date.</param>
        /// <param name="description">Valor inicial de la propiedad description.</param>
        /// <param name="categoryId">Valor inicial de la propiedad categoryId.</param>
        public static Event CreateEvent(global::System.Int32 id, global::System.String name, global::System.Byte[] date, global::System.String description, global::System.Int32 categoryId)
        {
            Event @event = new Event();
            @event.id = id;
            @event.name = name;
            @event.date = date;
            @event.description = description;
            @event.categoryId = categoryId;
            return @event;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] date
        {
            get
            {
                return StructuralObject.GetValidValue(_date);
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.Byte[] _date;
        partial void OndateChanging(global::System.Byte[] value);
        partial void OndateChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 categoryId
        {
            get
            {
                return _categoryId;
            }
            set
            {
                OncategoryIdChanging(value);
                ReportPropertyChanging("categoryId");
                _categoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("categoryId");
                OncategoryIdChanged();
            }
        }
        private global::System.Int32 _categoryId;
        partial void OncategoryIdChanging(global::System.Int32 value);
        partial void OncategoryIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> commentId
        {
            get
            {
                return _commentId;
            }
            set
            {
                OncommentIdChanging(value);
                ReportPropertyChanging("commentId");
                _commentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("commentId");
                OncommentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _commentId;
        partial void OncommentIdChanging(Nullable<global::System.Int32> value);
        partial void OncommentIdChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_Category_Event", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("PracticaMaDModel.FK_Category_Event", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("PracticaMaDModel.FK_Category_Event", "Category").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("PracticaMaDModel.FK_Category_Event", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("PracticaMaDModel.FK_Category_Event", "Category", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_Event_Comment", "Comment")]
        public EntityCollection<Comment> Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("PracticaMaDModel.FK_Event_Comment", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("PracticaMaDModel.FK_Event_Comment", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_Event_Recommendation", "Recommendation")]
        public EntityCollection<Recommendation> Recommendations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recommendation>("PracticaMaDModel.FK_Event_Recommendation", "Recommendation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recommendation>("PracticaMaDModel.FK_Event_Recommendation", "Recommendation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="Recommendation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recommendation : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Recommendation.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="text">Valor inicial de la propiedad text.</param>
        /// <param name="eventId">Valor inicial de la propiedad eventId.</param>
        /// <param name="usersGroupId">Valor inicial de la propiedad usersGroupId.</param>
        public static Recommendation CreateRecommendation(global::System.Int32 id, global::System.String text, global::System.Int32 eventId, global::System.Int32 usersGroupId)
        {
            Recommendation recommendation = new Recommendation();
            recommendation.id = id;
            recommendation.text = text;
            recommendation.eventId = eventId;
            recommendation.usersGroupId = usersGroupId;
            return recommendation;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String text
        {
            get
            {
                return _text;
            }
            set
            {
                OntextChanging(value);
                ReportPropertyChanging("text");
                _text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("text");
                OntextChanged();
            }
        }
        private global::System.String _text;
        partial void OntextChanging(global::System.String value);
        partial void OntextChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 eventId
        {
            get
            {
                return _eventId;
            }
            set
            {
                OneventIdChanging(value);
                ReportPropertyChanging("eventId");
                _eventId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eventId");
                OneventIdChanged();
            }
        }
        private global::System.Int32 _eventId;
        partial void OneventIdChanging(global::System.Int32 value);
        partial void OneventIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usersGroupId
        {
            get
            {
                return _usersGroupId;
            }
            set
            {
                OnusersGroupIdChanging(value);
                ReportPropertyChanging("usersGroupId");
                _usersGroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usersGroupId");
                OnusersGroupIdChanged();
            }
        }
        private global::System.Int32 _usersGroupId;
        partial void OnusersGroupIdChanging(global::System.Int32 value);
        partial void OnusersGroupIdChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_Event_Recommendation", "Event")]
        public Event Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("PracticaMaDModel.FK_Event_Recommendation", "Event").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("PracticaMaDModel.FK_Event_Recommendation", "Event").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Event> EventReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("PracticaMaDModel.FK_Event_Recommendation", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Event>("PracticaMaDModel.FK_Event_Recommendation", "Event", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UsersGroup_Recommendation", "UsersGroup")]
        public UsersGroup UsersGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsersGroup>("PracticaMaDModel.FK_UsersGroup_Recommendation", "UsersGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsersGroup>("PracticaMaDModel.FK_UsersGroup_Recommendation", "UsersGroup").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UsersGroup> UsersGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsersGroup>("PracticaMaDModel.FK_UsersGroup_Recommendation", "UsersGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UsersGroup>("PracticaMaDModel.FK_UsersGroup_Recommendation", "UsersGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="UserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserProfile : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UserProfile.
        /// </summary>
        /// <param name="loginName">Valor inicial de la propiedad loginName.</param>
        /// <param name="enPassword">Valor inicial de la propiedad enPassword.</param>
        /// <param name="firstName">Valor inicial de la propiedad firstName.</param>
        /// <param name="surname">Valor inicial de la propiedad surname.</param>
        /// <param name="email">Valor inicial de la propiedad email.</param>
        /// <param name="language">Valor inicial de la propiedad language.</param>
        /// <param name="country">Valor inicial de la propiedad country.</param>
        public static UserProfile CreateUserProfile(global::System.String loginName, global::System.String enPassword, global::System.String firstName, global::System.String surname, global::System.String email, global::System.String language, global::System.String country)
        {
            UserProfile userProfile = new UserProfile();
            userProfile.loginName = loginName;
            userProfile.enPassword = enPassword;
            userProfile.firstName = firstName;
            userProfile.surname = surname;
            userProfile.email = email;
            userProfile.language = language;
            userProfile.country = country;
            return userProfile;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String loginName
        {
            get
            {
                return _loginName;
            }
            set
            {
                if (_loginName != value)
                {
                    OnloginNameChanging(value);
                    ReportPropertyChanging("loginName");
                    _loginName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("loginName");
                    OnloginNameChanged();
                }
            }
        }
        private global::System.String _loginName;
        partial void OnloginNameChanging(global::System.String value);
        partial void OnloginNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String enPassword
        {
            get
            {
                return _enPassword;
            }
            set
            {
                OnenPasswordChanging(value);
                ReportPropertyChanging("enPassword");
                _enPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("enPassword");
                OnenPasswordChanged();
            }
        }
        private global::System.String _enPassword;
        partial void OnenPasswordChanging(global::System.String value);
        partial void OnenPasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String surname
        {
            get
            {
                return _surname;
            }
            set
            {
                OnsurnameChanging(value);
                ReportPropertyChanging("surname");
                _surname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("surname");
                OnsurnameChanged();
            }
        }
        private global::System.String _surname;
        partial void OnsurnameChanging(global::System.String value);
        partial void OnsurnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String language
        {
            get
            {
                return _language;
            }
            set
            {
                OnlanguageChanging(value);
                ReportPropertyChanging("language");
                _language = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("language");
                OnlanguageChanged();
            }
        }
        private global::System.String _language;
        partial void OnlanguageChanging(global::System.String value);
        partial void OnlanguageChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> usersGroupId
        {
            get
            {
                return _usersGroupId;
            }
            set
            {
                OnusersGroupIdChanging(value);
                ReportPropertyChanging("usersGroupId");
                _usersGroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usersGroupId");
                OnusersGroupIdChanged();
            }
        }
        private Nullable<global::System.Int32> _usersGroupId;
        partial void OnusersGroupIdChanging(Nullable<global::System.Int32> value);
        partial void OnusersGroupIdChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UserProfile_Comment", "Comment")]
        public EntityCollection<Comment> Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("PracticaMaDModel.FK_UserProfile_Comment", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("PracticaMaDModel.FK_UserProfile_Comment", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UsersGroup_UserProfile", "UsersGroup")]
        public UsersGroup UsersGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsersGroup>("PracticaMaDModel.FK_UsersGroup_UserProfile", "UsersGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsersGroup>("PracticaMaDModel.FK_UsersGroup_UserProfile", "UsersGroup").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UsersGroup> UsersGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsersGroup>("PracticaMaDModel.FK_UsersGroup_UserProfile", "UsersGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UsersGroup>("PracticaMaDModel.FK_UsersGroup_UserProfile", "UsersGroup", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "UserProfile_UserGroups", "UsersGroup")]
        public EntityCollection<UsersGroup> UsersGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UsersGroup>("PracticaMaDModel.UserProfile_UserGroups", "UsersGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UsersGroup>("PracticaMaDModel.UserProfile_UserGroups", "UsersGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="UsersGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsersGroup : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UsersGroup.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="description">Valor inicial de la propiedad description.</param>
        /// <param name="userId">Valor inicial de la propiedad userId.</param>
        public static UsersGroup CreateUsersGroup(global::System.Int32 id, global::System.String name, global::System.String description, global::System.Int32 userId)
        {
            UsersGroup usersGroup = new UsersGroup();
            usersGroup.id = id;
            usersGroup.name = name;
            usersGroup.description = description;
            usersGroup.userId = userId;
            return usersGroup;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                OnuserIdChanging(value);
                ReportPropertyChanging("userId");
                _userId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userId");
                OnuserIdChanged();
            }
        }
        private global::System.Int32 _userId;
        partial void OnuserIdChanging(global::System.Int32 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> recommendationId
        {
            get
            {
                return _recommendationId;
            }
            set
            {
                OnrecommendationIdChanging(value);
                ReportPropertyChanging("recommendationId");
                _recommendationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recommendationId");
                OnrecommendationIdChanged();
            }
        }
        private Nullable<global::System.Int32> _recommendationId;
        partial void OnrecommendationIdChanging(Nullable<global::System.Int32> value);
        partial void OnrecommendationIdChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UsersGroup_Recommendation", "Recommendation")]
        public EntityCollection<Recommendation> Recommendations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recommendation>("PracticaMaDModel.FK_UsersGroup_Recommendation", "Recommendation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recommendation>("PracticaMaDModel.FK_UsersGroup_Recommendation", "Recommendation", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UsersGroup_UserProfile", "UserProfile")]
        public EntityCollection<UserProfile> UserProfiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserProfile>("PracticaMaDModel.FK_UsersGroup_UserProfile", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserProfile>("PracticaMaDModel.FK_UsersGroup_UserProfile", "UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "UserProfile_UserGroups", "UserProfile")]
        public EntityCollection<UserProfile> UserProfiles1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserProfile>("PracticaMaDModel.UserProfile_UserGroups", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserProfile>("PracticaMaDModel.UserProfile_UserGroups", "UserProfile", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
