//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_Category_Event", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaMaD.Model.Category), "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.Event), true)]
[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_Event_Comment", "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaMaD.Model.Event), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.Comment), true)]
[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_UserProfile_Comment", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaMaD.Model.UserProfile), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.Comment), true)]
[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_Event_Recommendation", "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaMaD.Model.Event), "Recommendation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.Recommendation), true)]
[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_UsersGroup_Recommendation", "UsersGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaMaD.Model.UsersGroup), "Recommendation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.Recommendation), true)]
[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_UserProfile_UsersGroup_UserProfile", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaMaD.Model.UserProfile), "UserProfileUsersGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.UserProfileUsersGroup), true)]
[assembly: EdmRelationshipAttribute("PracticaMaDModel", "FK_UserProfile_UsersGroup_UsersGroup", "UsersGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.PracticaMaD.Model.UsersGroup), "UserProfileUsersGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.PracticaMaD.Model.UserProfileUsersGroup), true)]

#endregion

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class PracticaMaDEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto PracticaMaDEntities usando la cadena de conexión encontrada en la sección 'PracticaMaDEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public PracticaMaDEntities() : base("name=PracticaMaDEntities", "PracticaMaDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto PracticaMaDEntities.
        /// </summary>
        public PracticaMaDEntities(string connectionString) : base(connectionString, "PracticaMaDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto PracticaMaDEntities.
        /// </summary>
        public PracticaMaDEntities(EntityConnection connection) : base(connection, "PracticaMaDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Category> Category
        {
            get
            {
                if ((_Category == null))
                {
                    _Category = base.CreateObjectSet<Category>("Category");
                }
                return _Category;
            }
        }
        private ObjectSet<Category> _Category;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Comment> Comment
        {
            get
            {
                if ((_Comment == null))
                {
                    _Comment = base.CreateObjectSet<Comment>("Comment");
                }
                return _Comment;
            }
        }
        private ObjectSet<Comment> _Comment;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Event> Event
        {
            get
            {
                if ((_Event == null))
                {
                    _Event = base.CreateObjectSet<Event>("Event");
                }
                return _Event;
            }
        }
        private ObjectSet<Event> _Event;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Recommendation> Recommendation
        {
            get
            {
                if ((_Recommendation == null))
                {
                    _Recommendation = base.CreateObjectSet<Recommendation>("Recommendation");
                }
                return _Recommendation;
            }
        }
        private ObjectSet<Recommendation> _Recommendation;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UserProfile> UserProfile
        {
            get
            {
                if ((_UserProfile == null))
                {
                    _UserProfile = base.CreateObjectSet<UserProfile>("UserProfile");
                }
                return _UserProfile;
            }
        }
        private ObjectSet<UserProfile> _UserProfile;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UserProfileUsersGroup> UserProfileUsersGroup
        {
            get
            {
                if ((_UserProfileUsersGroup == null))
                {
                    _UserProfileUsersGroup = base.CreateObjectSet<UserProfileUsersGroup>("UserProfileUsersGroup");
                }
                return _UserProfileUsersGroup;
            }
        }
        private ObjectSet<UserProfileUsersGroup> _UserProfileUsersGroup;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UsersGroup> UsersGroup
        {
            get
            {
                if ((_UsersGroup == null))
                {
                    _UsersGroup = base.CreateObjectSet<UsersGroup>("UsersGroup");
                }
                return _UsersGroup;
            }
        }
        private ObjectSet<UsersGroup> _UsersGroup;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Category. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCategory(Category category)
        {
            base.AddObject("Category", category);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Comment. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToComment(Comment comment)
        {
            base.AddObject("Comment", comment);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Event. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEvent(Event @event)
        {
            base.AddObject("Event", @event);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Recommendation. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRecommendation(Recommendation recommendation)
        {
            base.AddObject("Recommendation", recommendation);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UserProfile. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUserProfile(UserProfile userProfile)
        {
            base.AddObject("UserProfile", userProfile);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UserProfileUsersGroup. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUserProfileUsersGroup(UserProfileUsersGroup userProfileUsersGroup)
        {
            base.AddObject("UserProfileUsersGroup", userProfileUsersGroup);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UsersGroup. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsersGroup(UsersGroup usersGroup)
        {
            base.AddObject("UsersGroup", usersGroup);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Category.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        public static Category CreateCategory(global::System.Int64 id, global::System.String name)
        {
            Category category = new Category();
            category.id = id;
            category.name = name;
            return category;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_Category_Event", "Event")]
        public EntityCollection<Event> Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Event>("PracticaMaDModel.FK_Category_Event", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Event>("PracticaMaDModel.FK_Category_Event", "Event", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Comment.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="date">Valor inicial de la propiedad date.</param>
        /// <param name="text">Valor inicial de la propiedad text.</param>
        /// <param name="eventId">Valor inicial de la propiedad eventId.</param>
        /// <param name="userProfileId">Valor inicial de la propiedad userProfileId.</param>
        public static Comment CreateComment(global::System.Int64 id, global::System.Byte[] date, global::System.String text, global::System.Int64 eventId, global::System.Int64 userProfileId)
        {
            Comment comment = new Comment();
            comment.id = id;
            comment.date = date;
            comment.text = text;
            comment.eventId = eventId;
            comment.userProfileId = userProfileId;
            return comment;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] date
        {
            get
            {
                return StructuralObject.GetValidValue(_date);
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.Byte[] _date;
        partial void OndateChanging(global::System.Byte[] value);
        partial void OndateChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String text
        {
            get
            {
                return _text;
            }
            set
            {
                OntextChanging(value);
                ReportPropertyChanging("text");
                _text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("text");
                OntextChanged();
            }
        }
        private global::System.String _text;
        partial void OntextChanging(global::System.String value);
        partial void OntextChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 eventId
        {
            get
            {
                return _eventId;
            }
            set
            {
                OneventIdChanging(value);
                ReportPropertyChanging("eventId");
                _eventId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eventId");
                OneventIdChanged();
            }
        }
        private global::System.Int64 _eventId;
        partial void OneventIdChanging(global::System.Int64 value);
        partial void OneventIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userProfileId
        {
            get
            {
                return _userProfileId;
            }
            set
            {
                OnuserProfileIdChanging(value);
                ReportPropertyChanging("userProfileId");
                _userProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userProfileId");
                OnuserProfileIdChanged();
            }
        }
        private global::System.Int64 _userProfileId;
        partial void OnuserProfileIdChanging(global::System.Int64 value);
        partial void OnuserProfileIdChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_Event_Comment", "Event")]
        public Event Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("PracticaMaDModel.FK_Event_Comment", "Event").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("PracticaMaDModel.FK_Event_Comment", "Event").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Event> EventReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("PracticaMaDModel.FK_Event_Comment", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Event>("PracticaMaDModel.FK_Event_Comment", "Event", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UserProfile_Comment", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("PracticaMaDModel.FK_UserProfile_Comment", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("PracticaMaDModel.FK_UserProfile_Comment", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("PracticaMaDModel.FK_UserProfile_Comment", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("PracticaMaDModel.FK_UserProfile_Comment", "UserProfile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Event : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Event.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="date">Valor inicial de la propiedad date.</param>
        /// <param name="description">Valor inicial de la propiedad description.</param>
        /// <param name="categoryId">Valor inicial de la propiedad categoryId.</param>
        public static Event CreateEvent(global::System.Int64 id, global::System.String name, global::System.Byte[] date, global::System.String description, global::System.Int64 categoryId)
        {
            Event @event = new Event();
            @event.id = id;
            @event.name = name;
            @event.date = date;
            @event.description = description;
            @event.categoryId = categoryId;
            return @event;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] date
        {
            get
            {
                return StructuralObject.GetValidValue(_date);
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.Byte[] _date;
        partial void OndateChanging(global::System.Byte[] value);
        partial void OndateChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 categoryId
        {
            get
            {
                return _categoryId;
            }
            set
            {
                OncategoryIdChanging(value);
                ReportPropertyChanging("categoryId");
                _categoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("categoryId");
                OncategoryIdChanged();
            }
        }
        private global::System.Int64 _categoryId;
        partial void OncategoryIdChanging(global::System.Int64 value);
        partial void OncategoryIdChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_Category_Event", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("PracticaMaDModel.FK_Category_Event", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("PracticaMaDModel.FK_Category_Event", "Category").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("PracticaMaDModel.FK_Category_Event", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("PracticaMaDModel.FK_Category_Event", "Category", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_Event_Comment", "Comment")]
        public EntityCollection<Comment> Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("PracticaMaDModel.FK_Event_Comment", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("PracticaMaDModel.FK_Event_Comment", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_Event_Recommendation", "Recommendation")]
        public EntityCollection<Recommendation> Recommendation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recommendation>("PracticaMaDModel.FK_Event_Recommendation", "Recommendation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recommendation>("PracticaMaDModel.FK_Event_Recommendation", "Recommendation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="Recommendation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recommendation : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Recommendation.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="text">Valor inicial de la propiedad text.</param>
        /// <param name="eventId">Valor inicial de la propiedad eventId.</param>
        /// <param name="usersGroupId">Valor inicial de la propiedad usersGroupId.</param>
        public static Recommendation CreateRecommendation(global::System.Int64 id, global::System.String text, global::System.Int64 eventId, global::System.Int64 usersGroupId)
        {
            Recommendation recommendation = new Recommendation();
            recommendation.id = id;
            recommendation.text = text;
            recommendation.eventId = eventId;
            recommendation.usersGroupId = usersGroupId;
            return recommendation;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String text
        {
            get
            {
                return _text;
            }
            set
            {
                OntextChanging(value);
                ReportPropertyChanging("text");
                _text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("text");
                OntextChanged();
            }
        }
        private global::System.String _text;
        partial void OntextChanging(global::System.String value);
        partial void OntextChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 eventId
        {
            get
            {
                return _eventId;
            }
            set
            {
                OneventIdChanging(value);
                ReportPropertyChanging("eventId");
                _eventId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eventId");
                OneventIdChanged();
            }
        }
        private global::System.Int64 _eventId;
        partial void OneventIdChanging(global::System.Int64 value);
        partial void OneventIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 usersGroupId
        {
            get
            {
                return _usersGroupId;
            }
            set
            {
                OnusersGroupIdChanging(value);
                ReportPropertyChanging("usersGroupId");
                _usersGroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usersGroupId");
                OnusersGroupIdChanged();
            }
        }
        private global::System.Int64 _usersGroupId;
        partial void OnusersGroupIdChanging(global::System.Int64 value);
        partial void OnusersGroupIdChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_Event_Recommendation", "Event")]
        public Event Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("PracticaMaDModel.FK_Event_Recommendation", "Event").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("PracticaMaDModel.FK_Event_Recommendation", "Event").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Event> EventReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("PracticaMaDModel.FK_Event_Recommendation", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Event>("PracticaMaDModel.FK_Event_Recommendation", "Event", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UsersGroup_Recommendation", "UsersGroup")]
        public UsersGroup UsersGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsersGroup>("PracticaMaDModel.FK_UsersGroup_Recommendation", "UsersGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsersGroup>("PracticaMaDModel.FK_UsersGroup_Recommendation", "UsersGroup").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UsersGroup> UsersGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsersGroup>("PracticaMaDModel.FK_UsersGroup_Recommendation", "UsersGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UsersGroup>("PracticaMaDModel.FK_UsersGroup_Recommendation", "UsersGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="UserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserProfile : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UserProfile.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="loginName">Valor inicial de la propiedad loginName.</param>
        /// <param name="enPassword">Valor inicial de la propiedad enPassword.</param>
        /// <param name="firstName">Valor inicial de la propiedad firstName.</param>
        /// <param name="surname">Valor inicial de la propiedad surname.</param>
        /// <param name="email">Valor inicial de la propiedad email.</param>
        /// <param name="language">Valor inicial de la propiedad language.</param>
        /// <param name="country">Valor inicial de la propiedad country.</param>
        public static UserProfile CreateUserProfile(global::System.Int64 id, global::System.String loginName, global::System.String enPassword, global::System.String firstName, global::System.String surname, global::System.String email, global::System.String language, global::System.String country)
        {
            UserProfile userProfile = new UserProfile();
            userProfile.id = id;
            userProfile.loginName = loginName;
            userProfile.enPassword = enPassword;
            userProfile.firstName = firstName;
            userProfile.surname = surname;
            userProfile.email = email;
            userProfile.language = language;
            userProfile.country = country;
            return userProfile;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String loginName
        {
            get
            {
                return _loginName;
            }
            set
            {
                OnloginNameChanging(value);
                ReportPropertyChanging("loginName");
                _loginName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("loginName");
                OnloginNameChanged();
            }
        }
        private global::System.String _loginName;
        partial void OnloginNameChanging(global::System.String value);
        partial void OnloginNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String enPassword
        {
            get
            {
                return _enPassword;
            }
            set
            {
                OnenPasswordChanging(value);
                ReportPropertyChanging("enPassword");
                _enPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("enPassword");
                OnenPasswordChanged();
            }
        }
        private global::System.String _enPassword;
        partial void OnenPasswordChanging(global::System.String value);
        partial void OnenPasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String surname
        {
            get
            {
                return _surname;
            }
            set
            {
                OnsurnameChanging(value);
                ReportPropertyChanging("surname");
                _surname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("surname");
                OnsurnameChanged();
            }
        }
        private global::System.String _surname;
        partial void OnsurnameChanging(global::System.String value);
        partial void OnsurnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String language
        {
            get
            {
                return _language;
            }
            set
            {
                OnlanguageChanging(value);
                ReportPropertyChanging("language");
                _language = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("language");
                OnlanguageChanged();
            }
        }
        private global::System.String _language;
        partial void OnlanguageChanging(global::System.String value);
        partial void OnlanguageChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UserProfile_Comment", "Comment")]
        public EntityCollection<Comment> Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("PracticaMaDModel.FK_UserProfile_Comment", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("PracticaMaDModel.FK_UserProfile_Comment", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UserProfile_UsersGroup_UserProfile", "UserProfileUsersGroup")]
        public EntityCollection<UserProfileUsersGroup> UserProfileUsersGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserProfileUsersGroup>("PracticaMaDModel.FK_UserProfile_UsersGroup_UserProfile", "UserProfileUsersGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserProfileUsersGroup>("PracticaMaDModel.FK_UserProfile_UsersGroup_UserProfile", "UserProfileUsersGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="UserProfileUsersGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserProfileUsersGroup : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UserProfileUsersGroup.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="userId">Valor inicial de la propiedad userId.</param>
        /// <param name="groupId">Valor inicial de la propiedad groupId.</param>
        public static UserProfileUsersGroup CreateUserProfileUsersGroup(global::System.Int64 id, global::System.Int64 userId, global::System.Int64 groupId)
        {
            UserProfileUsersGroup userProfileUsersGroup = new UserProfileUsersGroup();
            userProfileUsersGroup.id = id;
            userProfileUsersGroup.userId = userId;
            userProfileUsersGroup.groupId = groupId;
            return userProfileUsersGroup;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                OnuserIdChanging(value);
                ReportPropertyChanging("userId");
                _userId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userId");
                OnuserIdChanged();
            }
        }
        private global::System.Int64 _userId;
        partial void OnuserIdChanging(global::System.Int64 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 groupId
        {
            get
            {
                return _groupId;
            }
            set
            {
                OngroupIdChanging(value);
                ReportPropertyChanging("groupId");
                _groupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("groupId");
                OngroupIdChanged();
            }
        }
        private global::System.Int64 _groupId;
        partial void OngroupIdChanging(global::System.Int64 value);
        partial void OngroupIdChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UserProfile_UsersGroup_UserProfile", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("PracticaMaDModel.FK_UserProfile_UsersGroup_UserProfile", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("PracticaMaDModel.FK_UserProfile_UsersGroup_UserProfile", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("PracticaMaDModel.FK_UserProfile_UsersGroup_UserProfile", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("PracticaMaDModel.FK_UserProfile_UsersGroup_UserProfile", "UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UserProfile_UsersGroup_UsersGroup", "UsersGroup")]
        public UsersGroup UsersGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsersGroup>("PracticaMaDModel.FK_UserProfile_UsersGroup_UsersGroup", "UsersGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsersGroup>("PracticaMaDModel.FK_UserProfile_UsersGroup_UsersGroup", "UsersGroup").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UsersGroup> UsersGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UsersGroup>("PracticaMaDModel.FK_UserProfile_UsersGroup_UsersGroup", "UsersGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UsersGroup>("PracticaMaDModel.FK_UserProfile_UsersGroup_UsersGroup", "UsersGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PracticaMaDModel", Name="UsersGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsersGroup : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UsersGroup.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="description">Valor inicial de la propiedad description.</param>
        public static UsersGroup CreateUsersGroup(global::System.Int64 id, global::System.String name, global::System.String description)
        {
            UsersGroup usersGroup = new UsersGroup();
            usersGroup.id = id;
            usersGroup.name = name;
            usersGroup.description = description;
            return usersGroup;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UsersGroup_Recommendation", "Recommendation")]
        public EntityCollection<Recommendation> Recommendation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recommendation>("PracticaMaDModel.FK_UsersGroup_Recommendation", "Recommendation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recommendation>("PracticaMaDModel.FK_UsersGroup_Recommendation", "Recommendation", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PracticaMaDModel", "FK_UserProfile_UsersGroup_UsersGroup", "UserProfileUsersGroup")]
        public EntityCollection<UserProfileUsersGroup> UserProfileUsersGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserProfileUsersGroup>("PracticaMaDModel.FK_UserProfile_UsersGroup_UsersGroup", "UserProfileUsersGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserProfileUsersGroup>("PracticaMaDModel.FK_UserProfile_UsersGroup_UsersGroup", "UserProfileUsersGroup", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
